### ISSUE TITLE
Remove or hide a single address from MTW

### ISSUE THREAD

**Issue by snowkidind** [mytonwalletorg/mytonwallet#102]
It doesnt appear possible to remove an address from the ton wallet without wiping the entire wallet.

My issue is with the browser extension, not sure if other device types have this feature this or not.

For instance, I wish to remove about half of these wallets without wiping the entire thing and rekeying the mnemonics or relinking hardware devices for all other wallets:

<img width="304" alt="Screenshot 2024-06-15 at 11 48 02 AM" src="https://github.com/mytonwalletorg/mytonwallet/assets/8151653/d65339c8-72c7-4383-a53c-98e6591d53a5">

**Comment by mytonwalletorg** [comment]
Just go ahead and click Exit/Remove button in Settings.

**Comment by snowkidind** [comment]
Oh nice. no Idea why I didnt see that
