### ISSUE TITLE
Add support for EIP-6963

### ISSUE THREAD

**Issue by tiagofilipenunes** [mytonwalletorg/mytonwallet#103]
Please add support for EIP-6963 by announcing your provider on initalisation, preferable on page load with a content-script.

https://eips.ethereum.org/EIPS/eip-6963

This will allow for modern dapps to detect the MyTonWallet and support it accordingly. 

Relevant package that facilitates the process: https://github.com/wevm/mipd

Flow:
1. Open a dapp that supports EIP-6963 (https://app.carbondefi.xyz for example)
2. Open the window modal
3. MyTonWallet should show up (no need to select Metamask anymore)

**Comment by mytonwalletorg** [comment]
Thanks, but MyTonWallet does not support Ethereum network.
