### ISSUE TITLE
Application for Linux not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by vtamara** [mytonwalletorg/mytonwallet#109]
In my Ubuntu 24.04 for x86-64, I downloaded the Linux file available at https://mytonwallet.io/ (i.e https://github.com/mytonwalletorg/mytonwallet/releases/download/v1.20.11/MyTonWallet-x86_64.AppImage ), I added execution permission to it, but trying to run it from the shell produces:
```
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

Downgrading from fuse3 to fuse2 doesn't solve the problem but desinstalls required packages for ubuntu-desktop.

From the chrome extension of MyTonWallet, I have not been able to unfreeze the $MY rewards that I have and that should be unfreezed before tomorrow.  
I cannot find any support group or bot or email anywhere.

**Comment by Moormemar** [comment]
کمک کنید لطفا

در تاریخ یکشنبه ۳۰ ژوئن ۲۰۲۴،‏ ۰۳:۳۰ Vladimir Támara Patiño <
***@***.***> نوشت:

**Comment by mytonwalletorg** [comment]
@vtamara Please, refer to https://t.me/MyTonWalletSupport.
