### ISSUE TITLE
Button does not work correctly

### ISSUE THREAD

**Issue by danya7423** [mytonwalletorg/mytonwallet#11]
When you hover the mouse on the icon (button), the hover effect appears (the icon changes color). But nothing happens when you click.

If you hover the cursor just below, you see the hover effect and the cursor immediately becomes the pointer type.

> ![image](https://user-images.githubusercontent.com/84060706/199248024-32182905-152c-46fe-8d04-cd2e9a4df6a2.png)
> ![image](https://user-images.githubusercontent.com/84060706/199248123-9efd94b9-5222-4db3-90ef-700f6b4951be.png)
>

**Comment by danya7423** [comment]
OS: Windows
Browser: Opera

**Comment by teplulya** [comment]
@mytonwalletorg This has already been fixed
