### ISSUE TITLE
Add DEX integration on TON to Wallet

### ISSUE THREAD

**Issue by DeFiTON** [mytonwalletorg/mytonwallet#12]
Good afternoon. Can add +1 more DEX on the TON blockchain to integration for your Wallet. Thanks!

Project site:
- https://tegro.finance/

Documentation and source code:
- https://github.com/orgs/TegroTON/repositories

- Roadmap and information:
https://tegro.gitbook.io/en/dex/

How to add a project? Integration Example, [DefiLllama](https://defillama.com/protocol/tegro-finance):
https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/tegro/index.js

**Comment by troman29** [comment]
Предлагаю закрыть тикет, проект Тегро мертв

**Comment by mytonwalletorg** [comment]
> Предлагаю закрыть тикет, проект Тегро мертв

Were there any publications related to that?

**Comment by troman29** [comment]
> > Предлагаю закрыть тикет, проект Тегро мертв
> 
> Were there any publications related to that?

There has been no official news yet, but in the chat https://t.me/tonmoonru people write about problems with the work of Dex, about the loss of their money, support has not been responding for several weeks, and there is a huge wallet that actively drains tokens. Let's wait for the official news.

**Comment by troman29** [comment]
There was no official news, but Dex is not finished, there is no development, there is no liquidity, I went in and saw serious bugs. Let's close the issue
