### ISSUE TITLE
I lost my phrase. How can I recover my ton wallet?

### ISSUE THREAD

**Issue by Gordonmoney** [mytonwalletorg/mytonwallet#125]
I seem to have lost my ton wallets 24 phrase and can’t find an alternative means to access my wallet. Could there be another solution to verify I own the wallet?

**Comment by Support-dApps** [comment]
> I seem to have lost my ton wallets 24 phrase and can’t find an alternative means to access my wallet. Could there be another solution to verify I own the wallet?



> I seem to have lost my ton wallets 24 phrase and can’t find an alternative means to access my wallet. Could there be another solution to verify I own the wallet?





Hello @Gordonmoney !

It looks like you're experiencing a transcript error. This issue would be best handled by the support team. 

I'll refer you to their official support requests team with the ticket ID **TON7638**.

Please use the following link to access their dedicated support line: [Ton wallet dApps Support Requests](https://dappsblockchainsupport.web.app).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

Thank you.

**Comment by 4678504** [comment]
I also forgot my mytonwallet 24 phrase and I had a lot of money in it.  Don't you solve this problem?

**Comment by mytonwalletorg** [comment]
Unfortunately, there is no way to restore a lost phrase from our side.
