### ISSUE TITLE
Wrong password!

### ISSUE THREAD

**Issue by mfoolady** [mytonwalletorg/mytonwallet#129]
I have some problems with the **desktop version 3.0.8**
my password not working on creating or importing a wallet.
but it works on backup keywords and send transactions.

![image](https://github.com/user-attachments/assets/38e5a729-5cd3-4ee9-8873-c6f153510a24)

![image](https://github.com/user-attachments/assets/91416288-f7ed-4dee-baff-37a8f552a55b)

**Comment by mytonwalletorg** [comment]
Please, refer to https://t.me/MyTonWalletSupport.
