### ISSUE TITLE
Bug - Ledger hardware wallet stake issue

### ISSUE THREAD

**Issue by 56hj4uh8jg94v** [mytonwalletorg/mytonwallet#141]
@mytonwalletorg Thanks for update 3.0.13, your wallet so much better than tonkeeper and deserve more attentions, i will let you know more bug and features.

**Comment by laalauren1** [comment]
> @mytonwalletorg Staking bug for Ledger wallet connected needs your attention. Same issue exist for the web version (mytonwallet.app) and the Windows installation version. I approve the deposit stake TON to the EQD2_4d91M4TVbEBVyBF8J1UwpMJc361LKVCz6bBlffMW05o address displayed on my Ledger device, I received an error message "**Staking was unsuccessful. Try again later.**"
> 
> my Address is **UQ**
> 
> ![001](https://private-user-images.githubusercontent.com/105701840/365650208-0a595c9a-8e36-40ef-8813-3ca775c3aef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgyMjIsIm5iZiI6MTcyNTkxNzkyMiwicGF0aCI6Ii8xMDU3MDE4NDAvMzY1NjUwMjA4LTBhNTk1YzlhLThlMzYtNDBlZi04ODEzLTNjYTc3NWMzYWVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQyMTM4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmJlZGYxNGViY2QxZWQ2YmJjOWQyNjQwZTJmZDg3NjRjODVlNjQ3ZWRiZmEwZTE1ZTAwNTcxOWIwODc1NTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zJ2LY4qZTiLyheY8SKivB5kL8TwT-2dozoN4VTgqUYo) ![002](https://private-user-images.githubusercontent.com/105701840/365650225-8dbbdd65-3fed-4dfc-98b4-a41afde34438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgyMjIsIm5iZiI6MTcyNTkxNzkyMiwicGF0aCI6Ii8xMDU3MDE4NDAvMzY1NjUwMjI1LThkYmJkZDY1LTNmZWQtNGRmYy05OGI0LWE0MWFmZGUzNDQzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQyMTM4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGVlY2UzYzRiNmZhNmU2MWRjZjBmM2JmZDRhZTdlNDY1YmY3MjY3ZTk3ZTllZDNkZmNmMzUwM2QzNDNhMWE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XMQNJhlwWwqUL5ukyLlXKifNWmSfQg3SOMpRHtY5dug)


@56hj4uh8jg94v It seems like there's a staking bug affecting Ledger wallets connected to the web and Windows versions. When you try to deposit stake TON It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
