### ISSUE TITLE
Bugs report version 3.0.18

### ISSUE THREAD

**Issue by 56hj4uh8jg94v** [mytonwalletorg/mytonwallet#152]
@mytonwalletorg The merge of version [3.0.17 @](https://github.com/mytonwalletorg/mytonwallet/tree/v3.0.17) and refactored code caused various issues.

1) fixed

2) fixed

3) fixed

I appreciate your efforts in advance and if I see somethings else, I'll let you know it.

**Comment by 56hj4uh8jg94v** [comment]
only for Firefox show error below at end of the load.

![001](https://github.com/user-attachments/assets/edb4891c-36c2-4cda-8d73-8b53e7534902)

**Comment by mytonwalletorg** [comment]
Hi @56hj4uh8jg94v Thanks for your report. v3.0.19 is release to mytonwallet.app. Please confirm it fixes your issues.

**Comment by 56hj4uh8jg94v** [comment]
@mytonwalletorg Hi, Thanks for the super quick fix! Your response time was amazing—really appreciate it!

I can confirm the issue **1** and **3** fixed, The last activity still does not reveal the spam NFT I received, which is fine, but there is an issue that requires your investigation. Meanwhile, it could be beneficial to hide transaction (NFTs) that have been identified as spam.

**Comment by 56hj4uh8jg94v** [comment]
UI update not work properly for valuation section, if you pick Yuan or US Dollar, the UI will not update unless you refresh the page manually.

![002](https://github.com/user-attachments/assets/7ec0b4a7-daf9-411f-ad9a-65db799ea7bf)

**Comment by 56hj4uh8jg94v** [comment]
@mytonwalletorg 5 and 6 still exist for version 3.0.20 release to https://mytonwallet.app 

P.S. issue 6 does not exist in the Android build is only limited to the web version (Maybe for extensions)

**Comment by mytonwalletorg** [comment]
Hi @56hj4uh8jg94v, can you confirm the 5 is fixed with the latest version?

**Comment by 56hj4uh8jg94v** [comment]
Hi @mytonwalletorg I can confirm the 5 fixed.

**Comment by mytonwalletorg** [comment]
Thank you! @56hj4uh8jg94v
