### ISSUE TITLE
CAN NOT SEND HAMESTER COIN

### ISSUE THREAD

**Issue by mohammadhossien67** [mytonwalletorg/mytonwallet#159]
![image](https://github.com/user-attachments/assets/f5b5c3a2-6a58-4e06-b451-6255f588ea43)
WHY????????????

**Comment by Rafsahi** [comment]
مشکل من هم دقیقا همین است

**Comment by Rafsahi** [comment]
متوجه شدم که ولت نمیتونه محاسبه کنه که هزینه انتقال چقدراست

**Comment by mytonwalletorg** [comment]
Please, refer to https://t.me/MyTonWalletSupport.
