### ISSUE TITLE
Seeds lost

### ISSUE THREAD

**Issue by Djamesito** [mytonwalletorg/mytonwallet#163]
Bonjour j'ai perdu ma phrase comment récupérer mon compte

**Comment by juliehtet** [comment]
### _****_

**Comment by Gambitx101** [comment]
do you still have the wallet active on your device. you can be able to brute force the seed phase

**Comment by Djamesito** [comment]
Non because i exit and After  i can't make the Seed you Can help me for force? Sorry my english IS not good

**Comment by mytonwalletorg** [comment]
Please, refer to https://t.me/MyTonWalletSupport
