### ISSUE TITLE
Mintless Points have to not be shown

### ISSUE THREAD

**Issue by cleverocheck** [mytonwalletorg/mytonwallet#167]
I saw Mintless Points, which I actually don't have (the mint term was from September 16 to September 26), and when I tried to exchange them, an error occurred in the blockchain, thus I lost 0.040744679 tones on commission, so this is not just a visual bug, but also leads to a loss of funds. To read more about the project visit https://t.me/mintless_technology/4.

**Comment by mytonwalletorg** [comment]
Fixed, thanks for the report.
