### ISSUE TITLE
Sudden withdrawal from the wallet will display 24 words of another wallet

### ISSUE THREAD

**Issue by mohamadfaqani** [mytonwalletorg/mytonwallet#168]
Hello friends, please someone help, it has been 3 weeks suddenly I exited the wallet and somehow as if it was a fresh start I was faced with the wallet creation page and used my secret words to return but the novel I entered I was faced with a list of currencies that were not for me I did this 3 times but the result was the same and after that I tried the second wallet I had and this time another wallet with other currencies was displayed. I contacted the support, but I have been facing this problem for 3 weeks now

**Comment by Amim65an** [comment]
تن از من کم شد ولی کتیزن و جم برای من نیومده

**Comment by mytonwalletorg** [comment]
Please, refer to https://t.me/MyTonWalletSupport
