### ISSUE TITLE
I was finding some problem i want to talk with you

### ISSUE THREAD

**Issue by tariqmahmood898** [mytonwalletorg/mytonwallet#175]
**Dear developer,** 

I have checked your project thoroughly. _Thank you for all the hard work you put into completing this project and making it open source. _ And I value your work and appreciate your talent. But there are some problems in this project, I want your help to solve them.

**And I have something personal to talk to you about this project.**

And I know you are very busy with your project, but I have to talk to you too
Kindly share your [email](tariqmahmood898@gmail.com) [telegram](https://t.me/raymdf) id or WhatsApp number with me

**Comment by mytonwalletorg** [comment]
Hi, thanks, please, refer to https://t.me/MyTonWalletSupport

**Comment by kosmoss538** [comment]
> **Уважаемый разработчик,**
> 
> Я тщательно проверил ваш проект. _Спасибо вам за всю ту тяжёлую работу, которую вы вложили в завершение этого проекта и превращение его в проект с открытым исходным кодом. _ И я ценю вашу работу и ваш талант. Но в этом проекте есть некоторые проблемы, и я хочу, чтобы вы помогли их решить.
> 
> **И у меня есть кое-что личное, о чём я хочу поговорить с вами об этом проекте.**
> 
> И я знаю, что вы очень заняты своим проектом, но мне тоже нужно с вами поговорить Пожалуйста, поделитесь со мной своим [электронным адресом](tariqmahmood898@gmail.com) [идентификатором в Telegram](https://t.me/raymdf) или номером WhatsApp
