### ISSUE TITLE
Problem with wallet

### ISSUE THREAD

**Issue by BythewayIbrokhim** [mytonwalletorg/mytonwallet#178]
Forgot the password of my wallet, any ideas?

**Comment by Annawoody** [comment]
If you've forgotten the password for your wallet, the best thing to do is to reach out to the support team.I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonkeeper Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@BythewayIbrokhim

**Comment by BythewayIbrokhim** [comment]
I can't restore access to the wallet since the version has been updated and I have 24 secret phrases I have only 12 saved

**Comment by Annawoody** [comment]
Did you talk to the support team about it yet ? 
@BythewayIbrokhim

**Comment by BythewayIbrokhim** [comment]
> Forgot the password of my wallet, any ideas?
