### ISSUE TITLE
Add support of TON Storage hosted sites via Proxy

### ISSUE THREAD

**Issue by air3ijai** [mytonwalletorg/mytonwallet#23]
Hello,

This is just a follow up of the discussion we recently had with @justdmitry - [ Access TON Site on TON Storage via TON Proxy #677](https://github.com/ton-blockchain/ton/issues/677#issuecomment-1556272232).

It will be very useful to add support of the TON Sites stored on the TON Storage.

Thanks!

**Comment by troman29** [comment]
@mytonwalletorg This issue is solved, isn't it? Let's close a issue (or give me the rights)

**Comment by air3ijai** [comment]
Just checked - http://just-for-test.ton and http://just-dmitry.ton works now.

Thank you for the update!
