### ISSUE TITLE
Wrong result from wallet when sending transaction.

### ISSUE THREAD

**Issue by purpleguy99** [mytonwalletorg/mytonwallet#32]
Actually, i tried to send transaction request to the mytonwallet HTTP Bridge and got some invalid results.

![image](https://github.com/mytonwalletorg/mytonwallet/assets/89442150/186336d5-3d3e-4303-ae2f-6eae1d0c04ef)

You can see that result field of response of "SendTransactionRequest" is "ok". But in TonConnect 2.0 it must return BOC of transaction result in Base64.

**Comment by sadensmol** [comment]
@purpleguy99 Hey, thanks for raising this issue. I faced into similar one, maybe you can help. Actually there is no docs on BoC format/structure here. Maybe you know where it's documented?
