### ISSUE TITLE
Can't set dns with ledger or move DNS NFT - address doesn't support on hardware wallet

### ISSUE THREAD

**Issue by gades** [mytonwalletorg/mytonwallet#42]
I'm trying to set update and seeng error - device doesn't support address (I did try to set both address types )

<img width="1728" alt="Screenshot 2024-01-19 at 21 24 49" src="https://github.com/mytonwalletorg/mytonwallet/assets/4200730/6467138e-b6f1-4c57-b821-4c1deafc162e">
![Uploading Screenshot 2024-01-19 at 21.24.49.png…]()

**Comment by mytonwalletorg** [comment]
This is also a limitation set by TON app for Ledger. We need to wait for further updates from them.

**Comment by ucalado81** [comment]
I can't transfer my NFT from the Ledger address to another in the MyTonWallet
![my](https://github.com/mytonwalletorg/mytonwallet/assets/166533367/be415021-7cb7-49d2-9e23-166ab6c82c66)
