### ISSUE TITLE
Do not connect to the browser extension Firefox

### ISSUE THREAD

**Issue by shadesoma** [mytonwalletorg/mytonwallet#51]
Seems you don't have installed MyTonWallet browser extension. 
But I have an extension.

Linux 5.15.131-1-MANJARO
Browser: Firefox 118.0b7

![изображение](https://github.com/mytonwallet/web-extension/assets/41644376/5b76c728-bb53-464d-a781-475a4f4e61cf)

**Comment by nikicat** [comment]
The same for me

**Comment by Tanha1359** [comment]
> به نظر می رسد افزونه مرورگر MyTonWallet را نصب نکرده اید. اما من یک پسوند دارم.
> 
> Linux 5.15.131-1-MANJARO مرورگر: Firefox 118.0b7
> 
> ![جداسازی](https://private-user-images.githubusercontent.com/41644376/302915927-5b76c728-bb53-464d-a781-475a4f4e61cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDc3MjYsIm5iZiI6MTcyNzQwNzQyNiwicGF0aCI6Ii80MTY0NDM3Ni8zMDI5MTU5MjctNWI3NmM3MjgtYmI1My00NjRkLWE3ODEtNDc1YTRmNGU2MWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAzMjM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3Yjk4ZTA3MDRkYmI3MTUzMWJlNGVlZmNiNzg4N2FmNGQ3ZGI2ODc3MGE0NzAzZTRmMmM3NzgyYTBhM2JhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-WH25gJWjoAa3QIq6CbBS809VfpkX7hDxTzAro7NgQE)

سلام واسه من هم اونطوری هست بلدی چطور حذف کنی

**Comment by mytonwalletorg** [comment]
Closing as likely fixed a long time ago.
