### ISSUE TITLE
Selling and transferring Telegram Numbers are impossible on Ledger wallet

### ISSUE THREAD

**Issue by sepehrmohamadi** [mytonwalletorg/mytonwallet#52]
When I tried to sell or transfer Telegram numbers it was not possible on Ledger wallet!

![image](https://github.com/mytonwalletorg/mytonwallet/assets/18723838/ea90c8b5-0b55-4d2c-9935-fb463856d899)

![image](https://github.com/mytonwalletorg/mytonwallet/assets/18723838/19a2f038-f2d2-42db-9b0e-a807cc80eb0a)

**Comment by mytonwalletorg** [comment]
The error is correct, you need to wait until Ledger supports it.
