### ISSUE TITLE
Can't withdraw from wallet

### ISSUE THREAD

**Issue by sstrokin** [mytonwalletorg/mytonwallet#55]
Today I have been unable to transfer TON from my wallet in conjunction with the Ledger to the exchange all day. The operation does not work. What could be the reason? The first transaction was successful. All other subsequent ones fail. There is a clock icon next to the operation; after closing the wallet and then opening it, this operation is no longer displayed in the history and you need to try to send again, and so on every time.

**Comment by Gedoxa** [comment]
> 1111

**Comment by Gedoxa** [comment]
https://github.com/mytonwalletorg/mytonwallet/issues/55
