### ISSUE TITLE
NFT from the Ledger

### ISSUE THREAD

**Issue by ucalado81** [mytonwalletorg/mytonwallet#58]
I can't transfer my NFT from the Ledger address to another in the MyTonWallet
Is there any alternative?
![my](https://github.com/mytonwalletorg/mytonwallet/assets/166533367/1a92487d-e6c6-426c-9508-3adbaf0e7e2e)

**Comment by sambattsd** [comment]
I have the same problem, as it doesn't connect via fragment

**Comment by bu11ettrain** [comment]
same problem
why there are no any warnings about it?

**Comment by mytonwalletorg** [comment]
We added warning, and will release the updated version shortly.

**Comment by bu11ettrain** [comment]
is there ETA for this updated version?

**Comment by mytonwalletorg** [comment]
The updated version will only contain better warnings. Unfortunately, sending NFT is not supported by the Ledger TON app itself (the one in Ledger Live), we can not affect that. We do know, there is a new version of that app in developement at the moment, but they provide no ETA.
