### ISSUE TITLE
Mytonwalllet does not update

### ISSUE THREAD

**Issue by EvgeniyKorepov** [mytonwalletorg/mytonwallet#61]
The button receives focus but is not clickable. The caption on the button also disappeared.
Windows 10, MyTonWallet V1.19.12

![image](https://github.com/mytonwalletorg/mytonwallet/assets/35364901/34547c28-50d0-499e-9b8a-8eedb7537c6b)

**Comment by Yasnaasgari** [comment]
https://github.com/mytonwalletorg/mytonwallet.git

**Comment by Mazi48** [comment]
Hello, please release my wallet so that the rewards can be deposited

**Comment by mytonwalletorg** [comment]
> The button receives focus but is not clickable. The caption on the button also disappeared. Windows 10, MyTonWallet V1.19.12
> 
> ![image](https://private-user-images.githubusercontent.com/35364901/325488079-34547c28-50d0-499e-9b8a-8eedb7537c6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTU3OTIsIm5iZiI6MTcxNTM1NTQ5MiwicGF0aCI6Ii8zNTM2NDkwMS8zMjU0ODgwNzktMzQ1NDdjMjgtNTBkMC00OTllLTliOGEtOGVlZGI3NTM3YzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE1MzgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZWQyZDBiNTc0YzBiNWUyY2QzYjM5MmVmMWRjN2E3NjhlZjgwOTEwYjJkZjI4OTAzYTgzNjMzODE1ZGI2ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._eAHcZ-6AA9w9h_0E6TMj-p83VOoWXOK2hGtaLije5g)

Thanks for the report. That is fixed in v1.19.20.
