### ISSUE TITLE
Cannot restore wallet from 12-word secret phrase

### ISSUE THREAD

**Issue by ffrediani** [mytonwalletorg/mytonwallet#62]
I am trying to use MyTonWallet restoring a previous wallet I had however MyTonWallet required 24-word secret phrase to restore and doesn't give the option to use 12-word. If it was possible to generate a secret key with 12-word in another wallet software why isn't possible to use in MyTonWallet ?

**Comment by kraken7984** [comment]
`

**Comment by snowkidind** [comment]
This issue arises from people who have initialized a wallet in Trust wallet which ambiguously creates a TON wallet from 12 words using their method. Trust wallet does not support Jettons at all, and people need to import the 12 word key in order to retrieve Jettons erroneously sent to trust wallet recipient address. 

I've tried to create a program using the tonweb package to create a transaction from 12 word but was able to generate addresses but unable to create addresses consistent with the output of trust wallet.

Example
```

const { mnemonicToSeed } = require('tonweb-mnemonic')

const mnemonic = "the quick brown fox....."

;(async () => {
  try {
    const provider = tonweb.provider
    const seed = await mnemonicToSeed([mnemonic])
    const keyPair = tonweb.utils.nacl.sign.keyPair.fromSeed(seed)
    const wallet = new tonweb.wallet.all.v4R2(provider, {
      publicKey: keyPair.publicKey,
      wc: 0
    })
    const address = await wallet.getAddress()
    const nonBounceableAddress = address.toString(true, true, false)
    const balance = await provider.getBalance(nonBounceableAddress)
    console.log(nonBounceableAddress, balance)
  } catch (error) {
    console.log(error)
  }
})()
```

**Comment by mytonwalletorg** [comment]
@snowkidind I do not think `tonweb-mnemonic` supports passing 12-word mnemonic to `mnemonicToSeed`.

The proper solution here would be to write code that will extract the private key of a TON wallet based on 12-word mnemonic. We recently implemented a very similar approach for extracting from Ledger's 24-word mnemonic here: https://github.com/mytonwalletorg/ton-ledger-export/blob/master/src/index.js

You can try to adapt that code from Ledger's 24 words to Trust's 12 words.

Then the received private key (hex string) can be imported directly in MyTonWallet.

**Comment by mytonwalletorg** [comment]
There is no difference 12 or 24 words — if they are from Trust Wallet, they will not be accepted by MyTonWallet. So [extracting the private key](https://github.com/mytonwalletorg/mytonwallet/issues/62#issuecomment-2117477792) would be the solution.

**Comment by ffrediani** [comment]
12-word is simpler, so giving the use the possibility to choose either 12 or 24 would be better rather than just have 24 as an option, then any 12 or 24 word can be used on any Hot Wallet software that supports the coin.

**Comment by ffrediani** [comment]
Can't Mytonwallet simply accept 12-word in order to restore a wallet ?

**Comment by snowkidind** [comment]
> Then the received private key (hex string) can be imported directly in MyTonWallet.

I see no feature that allows this type of import. Desktop, browser extension or mobile.

**Comment by ffrediani** [comment]
What would be the block for Mytonwallet to accept 12 word recovery phrase along with the existing 24 word and also give the user the option to generate new seed with 12 word as well ?

**Comment by snowkidind** [comment]
So... yeah following up on finding my friends funds. Still no function to import address by private key. Are there any plans to add this?

<img width="441" alt="Screenshot 2024-06-05 at 10 42 54 AM" src="https://github.com/mytonwalletorg/mytonwallet/assets/8151653/78014784-64c9-46f8-870c-38a22cf9c774">

**Comment by ffrediani** [comment]
@mytonwalletorg what would take to develop a way to allow the create or import 12-word seed phrase on mytonwallet interface instead of just 24. Even if it uses another method, as long it has enough security is fine.
In other words how to avoid having to import a private key through a manual process and making it more friendly to the user without have to do trough commands.

@snowkidind the scenario you describe is pretty much what brought me here. Thanks for sharing your tentative. Perhaps a solution can be found to that that allows the user to choose either 12 or 24 words when creating or importing a wallet.

**Comment by AghilndR** [comment]
> @mytonwalletorg what would take to develop a way to allow the create or import 12-word seed phrase on mytonwallet interface instead of just 24. Even if it uses another method, as long it has enough security is fine. In other words how to avoid having to import a private key through a manual process and making it more friendly to the user without have to do trough commands.
> 
> @snowkidind the scenario you describe is pretty much what brought me here. Thanks for sharing your tentative. Perhaps a solution can be found to that that allows the user to choose either 12 or 24 words when creating or importing a wallet.

**Comment by mytonwalletorg** [comment]
> So... yeah following up on finding my friends funds. Still no function to import address by private key. Are there any plans to add this?

Just choose "24 Secret Words" and paste your hex private key.

**Comment by ffrediani** [comment]
@mytonwalletorg do you think is doable to have also the option to enter a 12-word seed or give the user option to generate both as per his preference ?

**Comment by snowkidind** [comment]
> Just choose "24 Secret Words" and paste your hex private key.

Are you kidding or is this an easter egg?

**Comment by snowkidind** [comment]
Ok I see the function made the latest update - thanks! But a couple issues have now presented themselves: 

1. the wallet derivation path isnt the same as the one trust wallet uses, so its no bueno. I am not sure which method trust wallet used so this is ambiguous. perhaps I can reach out to them and get an answer.

2. Now that I've successfully imported the wrong version of my friends wallet into myTonWallet, I want to remove it without wiping the 10 other wallets from different seed phrases I have within the app. How does one remove a single address from MTW?

I have notified trust wallet of their issue
https://github.com/trustwallet/wallet-core/issues/3898

**Comment by ffrediani** [comment]
@snowkidind please do so. TrustWallet is very very bad at communication. Very bad support system, they loose emails in between the interaction and are unable to be aware of the issue. But above all this issue needs to be treated.

Seems MyTonWallet needs these improvements and being limited to 24-word only is not a good thing. Add the 12-word support whenever possible please.

**Comment by mytonwalletorg** [comment]
> 2\. Now that I've successfully imported the wrong version of my friends wallet into myTonWallet, I want to remove it without wiping the 10 other wallets from different seed phrases I have within the app. How does one remove a single address from MTW?

Just use Settings > Exit or Remove Wallet.

**Comment by AghilndR** [comment]
> I am trying to use MyTonWallet restoring a previous wallet I had however MyTonWallet required 24-word secret phrase to restore and doesn't give the option to use 12-word. If it was possible to generate a secret key with 12-word in another wallet software why isn't possible to use in MyTonWallet ?

**Comment by seriabov** [comment]
@snowkidind  @mytonwalletorg Trust wallet uses `m/44'/607'/0'` as derivation path for TON. I changed the derivation path here - https://github.com/mytonwalletorg/ton-ledger-export/blob/master/src/index.js and it works with 12-word phrase

**Comment by Ajaxy** [comment]
> @snowkidind @mytonwalletorg Trust wallet uses `m/44'/607'/0'` as derivation path for TON. I changed the derivation path here - https://github.com/mytonwalletorg/ton-ledger-export/blob/master/src/index.js and it works with 12-word phrase

Can you please provide a code example or a diff?

**Comment by seriabov** [comment]
@Ajaxy I changed this line to get values at `m/44'/607'/0'`:
```javascript
const seedContainer = derivePath(`m/44'/607'/${index}'`, seed.toString('hex'));
```

**Comment by ffrediani** [comment]
Great thing. Hopefully 12 words can ve a standard option as well in order to make it more like most wallets.

> @snowkidind @mytonwalletorg Trust wallet uses `m/44'/607'/0'` as derivation path for TON. I changed the derivation path here - https://github.com/mytonwalletorg/ton-ledger-export/blob/master/src/index.js and it works with 12-word phrase

**Comment by snowkidind** [comment]
This resolves the issue of inadvertently sent jettons from trust wallet. using `m/44'/607'/${index}'` was the fix.

**Comment by Adekunlex40** [comment]
I have sent tron coin to my trust wallet , the transaction is confirmed but not added to my trust wallet balance. Kindly help me. I am using latest trust wallet apps, I have checked on trust wallet extension ; it is confirmed but not added to my trust wallet balance. Kindly help me
![Screenshot_20241126-064139](https://github.com/user-attachments/assets/c25a32df-9428-41c7-884f-7b0f30d447e3)
![Screenshot_20241126-064126](https://github.com/user-attachments/assets/72a965c0-05a5-4963-ad1a-49778cdb7da7)
![Screenshot_20241126-064139](https://github.com/user-attachments/assets/52a3e3a1-114c-4f0b-b654-31fc7fa0057b)

**Comment by mm8191** [comment]
New adress
UQDasWTnuOI4srBPkX9pufz71AV6UuJmApkUhAHeD8Kg2dHz

در تاریخ سه‌شنبه ۲۶ نوامبر ۲۰۲۴، ۹:۱۶ قبل‌ازظهر Adekunlex40 <
***@***.***> نوشت:

**Comment by mytonwalletorg** [comment]
This is now implemented.
