### ISSUE TITLE
Poor button language causing people to send NOT voucher to Burn address

### ISSUE THREAD

**Issue by snowkidind** [mytonwalletorg/mytonwallet#75]
The Button on the user interface to claim NOT tokens should read "Redeem NOT Vouchers" 

Because it currently reads "Burn Not Vouchers" people are using the other burn in the contextual drop down to send the Vouchers straight to the burn address.

Further the warning that comes states:

"You are going to BURN n NFT's..." This should also reflect the process that the user is claiming tokens for NFTs

Please fix to remove ambiguity of a normal burn and claiming NFTs

**Comment by mytonwalletorg** [comment]
Even if you use the other Burn item in the context menu, it will send vouchers to the proper contract, not the burn address.

Although, we agree that the naming is confusing, but it is used by the official Notcoin channels, so it would be even more confusing if we only try to re-word that on our side.
