### ISSUE TITLE
Can't set biometric authentication

### ISSUE THREAD

**Issue by MattRGX** [mytonwalletorg/mytonwallet#77]
Hello guys,

I'm having trouble right now when activating biometric authentication. 

It first ask me my pin code, then my finger print.
And after the finger print, it ask me the code again, then the finger print and so on. I'm kinda stuck on this "code / finger print" loop.

FYI :

Android 14
Calyx OS
Pixel 7
My Ton Wallet 1.19.28

Thanks for your help

**Comment by mytonwalletorg** [comment]
Hi, can you still reproduce this?

**Comment by MattRGX** [comment]
@mytonwalletorg 

Hello, now i can enable biometric authentication without trouble. But it is still not working properly. 
The app never ask my finger print when i open it. The settings is enabled but it looks like it is not.

Thanks

**Comment by mytonwalletorg** [comment]
> The app never ask my finger print when i open it.

That will be added soon.
