### ISSUE TITLE
Feature to hide spam/scam NFT

### ISSUE THREAD

**Issue by CageFox** [mytonwalletorg/mytonwallet#82]
There is tons of scam nfts in the TON network, there is no good method to destroy them

It will be useful feature to hide unwanted nft in the NFT tab of the wallet

**Comment by mytonwalletorg** [comment]
Hi, please update to the lastest MyTonWallet version — scam NFTs are already hidden by default.

**Comment by CageFox** [comment]
I have latest MyTonWallet 1.19.29
scam NFT present

![image](https://github.com/mytonwalletorg/mytonwallet/assets/1295382/31b06d38-33a7-427a-a595-4ac533b65805)

**Comment by mytonwalletorg** [comment]
I see, for those ones you can use the Burn feature.
