### ISSUE TITLE
Transaction Confirmation Modal Not Displayed After Long Inactivity on macOS 14.5

### ISSUE THREAD

**Issue by zeloras** [mytonwalletorg/mytonwallet#87]
### Issue Description:

I have encountered an issue with MyTonWallet 1.19.32 on macOS Version 14.5 (23F79). 

**Steps to Reproduce:**
1. Launch MyTonWallet and keep it running.
2. Leave the wallet minimized for several hours.
3. Attempt a transaction via [https://connect.mytonwallet.org/?no-redirect](https://connect.mytonwallet.org/?no-redirect).
4. Observe that the wallet window is brought back to focus, but the transaction confirmation modal is not displayed.

**Expected Behavior:**
When clicking on the transaction link after the wallet has been minimized for several hours, the transaction confirmation modal should appear reliably.

**Workaround:**
Closing and reopening the wallet, then clicking the transaction link again will display the transaction confirmation modal as expected.

**Environment:**
- MyTonWallet Version: 1.19.32
- macOS Version: 14.5 (23F79)

**Additional Information:**
This issue seems to occur when the wallet application remains minimized for an extended period. This problem does not occur if the wallet is closed and reopened before clicking the transaction link.

Could you please investigate this issue to ensure that the transaction confirmation modal appears consistently regardless of the wallet's state.

**Comment by mytonwalletorg** [comment]
@zeloras Can you still reproduce this with the latest version?

**Comment by zeloras** [comment]
@mytonwalletorg Good evening! Nope, it's fine. The popup confirmation shows up a little slowly, but it works fine. Thank you!
