### ISSUE TITLE
chrome plugin conflicting with Ton wallet extension

### ISSUE THREAD

**Issue by mikezavhoz** [mytonwalletorg/mytonwallet#9]
Hello. I installed your wallet plugin and tired to sign the transaction on https://demo.ston.fi and I recieved the error message. Once I contacted the ston.fi guys they said that "Yes maybe its override window.ton instance.  It’s looks like override of a ton wallet plug-in. So the error message is kinda valid. We should show “plug-in is overridden” error on this case but it’s nothing we can do against it." 

I assume you are using the same name space.

**Comment by mytonwalletorg** [comment]
Hi. What kind of error do you see? I tried running it with only classical TON wallet installed, and it did not work for me either (lots of "stores / AssetsStore / _fetchBalance > failed to fetch balance" errors).

**Comment by mikezavhoz** [comment]
PluginNowFoundError 

![image](https://user-images.githubusercontent.com/111587390/196245510-1cd6b3ee-728b-4075-8b10-d29e3215d037.png)

**Comment by mytonwalletorg** [comment]
I can not reproduce your issue. I can not even get to the screen you are showing here.

This is what I see:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/102837730/196366741-a5c139ef-a556-46cd-bf90-6a8ee64326d1.png">

**Comment by mytonwalletorg** [comment]
Feel free to re-open if it's still reproduced.
