### ISSUE TITLE
Не дошли ноткоины до получателя

### ISSUE THREAD

**Issue by Ura1601** [mytonwalletorg/mytonwallet#90]
![Screenshot_2024-06-04-12-54-46-579_com android chrome](https://github.com/mytonwalletorg/mytonwallet/assets/171647172/8e7a7099-10ac-45e9-a634-9378f17cbabf)
![Screenshot_2024-06-04-12-54-15-462_org mytonwallet app](https://github.com/mytonwalletorg/mytonwallet/assets/171647172/c8d8a5b5-fa6f-4ee1-9d61-fd9a86ec41ea)
Отправил ноткоины транзакция успешная но они не дошли

**Comment by yyy7u** [comment]
### ****

**Comment by mytonwalletorg** [comment]
Hello, please, refer to https://t.me/MyTonWalletSupport.
